import seedTowns from "./helper.js";



const raw_atwima_mponua_data = [
  "AGOGOSO",
  "MPASATIA",
  "NYINAHIN",
  "ABOABO",
  "ABODIEM",
  "ABOKYIKROM",
  "ADOMAKOKROM",
  "ADUKROM",
  "AFRIYIEKROM",
  "AKANTANSU NKWANTA",
  "AKWAKROM",
  "AMOFAKROM",
  "AMPATOKROM",
  "AMPOMA",
  "APPIAKROM",
  "ATTA PANYINKROM",
  "BAYEREBON NO.1",
  "BEPOSO",
  "BEYEDENKROM",
  "BOAKYEKROM",
  "BOATENKUROM",
  "BOBIEKROM",
  "BONWIRE",
  "BREDI",
  "DABOKROM",
  "DATANOKROM",
  "DESEREAGYA",
  "DODOWA",
  "DOMEABRA",
  "HIAMANKWA",
  "HWEDIAM",
  "J.J. KROM",
  "JAMIRAKROM",
  "JERUSALEM",
  "KAEBRE",
  "KALONGO",
  "KOFI DWUMAKROM",
  "KOFIABEKUROM",
  "KRAMOKROM",
  "KWABENAFORI",
  "KWADWO MENSAKROM",
  "KWAKU ADDAE",
  "KWARTENG",
  "MAMPONG ABEBRESE",
  "MANTUKWA",
  "MENHANDAN",
  "MMAWANINHA",
  "MMEHAME"
];

seedTowns(raw_atwima_mponua_data, "ghana", "ashanti", "atwima-mponua")