import seedTowns from "./helper.js";

const raw_bekwai_data = [
  "BEKWAI",
  "ABESEWA",
  "ABODOM",
  "ABUOSO",
  "ADJAMESU",
  "AHWIREM",
  "AKWEBETOSU",
  "AMOAFUL",
  "ANWIANKWANTA",
  "ASANSO",
  "ASECHERE",
  "BIRIBIWOMANMU",
  "BOAMAN",
  "BODOMA",
  "BOGYAWE",
  "BONI",
  "DADIASI",
  "DOMINASE",
  "DWUMAKRO",
  "EDWENASE",
  "ESSUMAJA",
  "FAAMAN",
  "HUNTADO",
  "KANSARE",
  "KOKOFU",
  "KOKOTRO",
  "KONIYAW",
  "KWAMAN",
  "MAHAME",
  "MENSINASI",
  "NEW ADAKWAI",
  "NTINANKO",
  "OCHERESO",
  "ODUMASE",
  "OFOASE-KOKOBEN",
  "OMANADUARE",
  "POANO",
  "SANFO",
  "SEBEDIE",
  "SENFI",
  "WIOSO"
];

seedTowns(raw_bekwai_data, "ghana", "ashanti", "bekwai")