import seedTowns from "./helper.js";



const raw_bosomtwe_data = [
  "KUNTANASE",
  "ABA ASE",
  "ABOASO",
  "ABONO",
  "ABORODWOM",
  "ABRANKESE",
  "ABUONTEM",
  "ADAGYA",
  "ADJAMAM",
  "ADUABEN",
  "ADUNKU",
  "ADWAFO KROM",
  "ADWAFO NEW TOWN",
  "ADWUMAM",
  "AKOKOFE",
  "AKWADUO",
  "AMAKOM",
  "AMANKWADEI",
  "ANYINATIASE",
  "APINKRA",
  "APUTUOGYA",
  "ASISIRIWA",
  "ATOBIASE",
  "AYOUM",
  "BEHIASE",
  "BEPOSO",
  "BONKORKOR",
  "DEDESUA",
  "DEDUAKO",
  "EDWINASE",
  "ESASO",
  "ESRESO",
  "FEYIASE",
  "HOMABENASE",
  "JACHIE",
  "KOKODEI",
  "KONKOMA",
  "MIM",
  "NEW BRODEKWANO",
  "NEW KOKOBRIKO",
  "NEW PIPIE VILLAGE",
  "NKOWI",
  "NKWANTA",
  "NNUASO",
  "NYAMIENI",
  "OBO",
  "OLD KOKOBRIKO",
  "ONWE NO.2",
  "OYOKO",
  "PATRIENSA",
  "PIASE",
  "PIPIE",
  "PRABON",
  "PRAMSO",
  "PRENYINASE",
  "SAWUA",
  "SWEDRU",
  "TETREFU",
  "TOAMFOM",
  "WOARAKOSE",
  "YAASE",
  "ADUAMPONG",
  "BONIAGYA",
  "BRODEKWANO",
  "FAHIAKOBO",
  "KOKWADO",
  "NKOWINKWANTA"
];

seedTowns(raw_bosomtwe_data, "ghana", "ashanti", "bosomtwe")