import seedTowns from "./helper.js";


const raw_kwabre_east_data = [
  "OVERSEAS",
  "NTAAMU",
  "ANYINAM",
  "AHWIAA",
  "ADONTEN",
  "MEDOMA",
  "AMOAKO",
  "ASENUA",
  "FAWOADE",
  "BAMPENASE",
  "ASAMANYA",
  "MAMPONTENG",
  "ACHIASE",
  "NKUBEM",
  "KOREA",
  "GYAMFI WONOO",
  "ABOASO",
  "ANYINASU",
  "TEWEBAABI",
  "NTONSO",
  "NEW ASONOMASO",
  "OLD ASONOMASO",
  "ADANWOMASE",
  "SAFO",
  "KASAAM",
  "SAKORA WONOO",
  "AHODWO",
  "WADIE ADWUMAKASE",
  "AKITIBOMO",
  "DUMANAFO",
  "ABIRA",
  "ADENSE",
  "KROBO",
  "ADEISINA",
  "ANTOA",
  "ABIREM",
  "ABIREM NEW SITE",
  "NWAMASE",
  "KENYASE",
  "BROFOYEDRU",
  "TRUBA",
  "TANO ADWUMAM",
  "ADWUMAM MANHYIA",
  "BOSORE"
];

seedTowns(raw_kwabre_east_data, "ghana", "ashanti", "kwabre-east")