import seedTowns from "./helper.js";



const raw_sekyere_central_data = [
  { town: "Abaasua" },
  { town: "Abenaso" },
  { town: "Abidwan" },
  { town: "Abonkosu" },
  { town: "Adukrom" },
  { town: "Adutwam" },
  { town: "Aframso" },
  { town: "Akyease" },
  { town: "Amangoase" },
  { town: "Amoamang" },
  { town: "Anankamadua" },
  { town: "Anansu" },
  { town: "Ankamabuoso" },
  { town: "Anwanya" },
  { town: "Asare Nkwanta" },
  { town: "Asuafu" },
  { town: "Asubuasu" },
  { town: "Asuogya" },
  { town: "Atonsu" },
  { town: "Atwea" },
  { town: "Balana" },
  { town: "Beposo" },
  { town: "Bimma" },
  { town: "Birim" },
  { town: "Bonkwaem" },
  { town: "Bonkrong" },
  { town: "Chokosi" },
  { town: "Congo" },
  { town: "Didaso" },
  { town: "Domakwai" },
  { town: "Domeabra" },
  { town: "Domi" },
  { town: "Esreso" },
  { town: "Fawomang" },
  { town: "Gariba Nkwanta" },
  { town: "Governor" },
  { town: "Gyetiase" },
  { town: "Issakakrom" },
  { town: "Jansa" },
  { town: "Jeduako" },
  { town: "Kroduase" },
  { town: "Kruwi" },
  { town: "Kwabena Akura" },
  { town: "Kwakye Dida" },
  { town: "Kwamang" },
  { town: "Kwame Dapaah" },
  { town: "Kyebi" },
  { town: "Kyekyebon" },
  { town: "Kyeyiase" },
  { town: "Marloo" },
  { town: "Medina" },
  { town: "Mentukwa" },
  { town: "Mpantunase" },
  { town: "Nantwibuom" },
  { town: "Njaya" },
  { town: "Nkokobudso" },
  { town: "Nkujua" },
  { town: "Nkwabirim" },
  { town: "Nsuta" },
  { town: "Nyameane" },
  { town: "Nyamebekyere" },
  { town: "Odumase" },
  { town: "Owuobonho" },
  { town: "Saasebonso" },
  { town: "Sankasaase" },
  { town: "Santasaase" },
  { town: "Sunkwae" },
  { town: "Tadieso" },
  { town: "Taylorkrom" },
  { town: "Yireso" }
];



seedTowns(raw_sekyere_central_data, "ghana", "ashanti", "sekyere-central")